### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by liach** [HundunStar/AutoTransfer#7]
1. Do you guys code C#? As I know the package name should not be upper camel case based on most style guides.
2. travis script should be

``` yaml
language: java
jdk:
      - oraclejdk8
      - oraclejdk7
      - openjdk7
      - openjdk6
script:
      - chmod +x gradlew
      - ./gradlew setupDecompWorkspace build
```
1. You guys might need a code style guide like [forge code style](https://github.com/ForgeEssentials/ForgeEssentials/blob/develop/misc/eclipseformatter.xml) or [google's](http://google.github.io/styleguide/javaguide.html).
2. You need to fix `build.gradle` [here](https://github.com/HundunStar/AutoTransfer/blob/d7e46956f36bf09f3febbf962aa257e00bb9c2bb/build.gradle#L20-L22) .
